#!/bin/bash
# Cleanup redundant documentation files

echo "🧹 Starting documentation cleanup..."

# Status reports (keep PROJECT_READY.md)
rm -f ./ADMIN_PAGES_STATUS.md ./ADMIN_PANEL_STATUS_REPORT.md
rm -f ./COMPLETE_STATUS.md ./COMPLETION_REPORT.md ./COMPLETION_SUMMARY.md
rm -f ./FINAL_STATUS*.md ./PROJECT_COMPLETE*.md
rm -f ./COMPREHENSIVE_STATUS.md ./FINAL_INTEGRATION_COMPLETE.md
rm -f ./FINAL_PROJECT_STATUS.md

# Implementation guides
rm -f ./ADMIN_IMPLEMENTATION_GUIDE.md ./IMPLEMENTATION_PLAN.md
rm -f ./IMPLEMENTATION_PLAN_56_PAGES.md ./IMPLEMENTATION_PROGRESS.md
rm -f ./IMPLEMENTATION_STATUS.md ./IMPLEMENTATION_STRATEGY.md
rm -f ./IMPLEMENTATION_VERIFIED.md ./ALL_PAGES_IMPLEMENTATION_PLAN.md

# Phase reports
rm -f ./PHASE*.md ./SESSION_*.md ./BIG4_*.md

# Admin reports
rm -f ./ADMIN_ENHANCEMENTS_COMPLETE.md ./ADMIN_PAGES_FIX.md
rm -f ./ADMIN_PANEL_*.md ./ADVANCED_ADMIN_COMPLETE.md
rm -f ./ALL_*.md

# Product/Import
rm -f ./PRODUCTS_*.md ./PRODUCT_*.md
rm -f ./IMPORT_*.md ./WOOCOMMERCE_IMPORT_*.md ./CSV_*.md
rm -f ./10_PRODUCTS_IMPORTED.md

# Bug fixes
rm -f ./BUG_FIXES.md ./CART_BUTTONS_FIX.md ./CSRF_FIXED.md
rm -f ./ERROR_403_FIXED.md ./LINKS_*.md ./SESSIONS_FIX*.md
rm -f ./RESOLVED_FINAL.md ./AXIOS_ERROR_FIXED.md

# Branding
rm -f ./BRANDING_*.md ./NAVY_GOLD_REDESIGN.md ./TWO_LOGO_STRATEGY.md
rm -f ./FULL_LOGO_UPDATE.md ./FOOTER_AND_COLORS_UPDATE.md

# Marathon/Progress reports
rm -f ./MARATHON_*.md ./MISSION_ACCOMPLISHED.md ./WORK_COMPLETED_TODAY.md
rm -f ./REALISTIC_MARATHON_PLAN.md

# Homepage
rm -f ./HOMEPAGE_*.md ./ENHANCED_HOMEPAGE_COMPLETE.md
rm -f ./DYNAMIC_HOMEPAGE_IMPLEMENTATION.md ./NEW_ARRIVALS_NEWSLETTER.md

# Miscellaneous
rm -f ./ANALYTICS_*.md ./API_WORKING.md ./FILTERS_LIVE_DOCUMENTATION.md
rm -f ./IMAGES_WORKING_LOCALLY.md ./MANUAL_PRODUCT_SELECTION.md
rm -f ./PREVIEW_PAGES_COMPLETE.md ./QUICK_*.md ./SEARCH_AUTOCOMPLETE_LIVE.md
rm -f ./SECTIONS_STATUS_REPORT.md ./SIDEBAR_UNIFICATION_FIX.md
rm -f ./UI_IMPROVEMENT*.md ./UPGRADE_*.md ./VISUAL_ROADMAP.md
rm -f ./PLACEHOLDER_PAGES_LIST.md ./PRIORITY_FIXES.md
rm -f ./ROUTE_*.md ./TESTING_GUIDE.md ./TEST_FLOW.md
rm -f ./TICKETS_SYSTEM_IMPLEMENTATION.md ./VAT_VALIDATION_IMPLEMENTATION.md
rm -f ./SECURITY_IMPLEMENTATION.md ./SETTINGS_STRUCTURE.md
rm -f ./PAYMENT_PAGES_IMPLEMENTATION.md ./OPTION_C_*.md
rm -f ./PAGE_TEMPLATES_*.md ./PRESTASHOP_REDESIGN_COMPLETE.md
rm -f ./PREMIUM_UI_REDESIGN.md ./PROFESSIONAL_HEADER_COMPLETE.md
rm -f ./MODERN_3D_DESIGN_COMPLETE.md ./LANGUAGE_IMPLEMENTATION.md
rm -f ./LICENSE_ANALYTICS.md ./LIVE_CHAT.md ./MARKETING.md
rm -f ./INTEGRATION_COMPLETE.md ./INDEX.md ./IMPROVEMENT_ROADMAP.md
rm -f ./FEATURE_*.md ./FIREWALL_COMPLETE.md ./FULL_WIDTH_AND_SECTIONS_COMPLETE.md
rm -f ./ECOMMERCE_FLOW_PLAN.md ./ENHANCED_FIREWALL_ADMIN_UI.md
rm -f ./DESIGN_ENHANCEMENT_PROPOSAL.md ./DEPLOYMENT_SUMMARY.md
rm -f ./DASHBOARD_COMPLETE.md ./CUSTOM_*.md ./CRUD_IMPLEMENTATION_COMPLETE.md
rm -f ./CLEANUP_COMPLETE_SUMMARY.md ./COMPLETE_FLOW_TESTING.md
rm -f ./COMPLETE_PAGE_INVENTORY.md ./COMPREHENSIVE_AUDIT_*.md
rm -f ./BUY_NOW_COMPLETE.md ./BEAUTIFUL_ADMIN_UI_PLAN.md
rm -f ./AUDIT_*.md ./NEXT_FEATURES_SUMMARY.md ./PROJECT_*.md
rm -f ./DELIVERY.md ./COUPONS.md ./COOKIES.md ./CONTACT_MESSAGES.md
rm -f ./CERTIFICATES.md ./CERTIFICATE_SETTINGS.md ./AUTOMATIONS.md

echo "✅ Cleanup complete!"
echo ""
echo "📊 Files remaining:"
ls -1 *.md 2>/dev/null | wc -l
echo ""
echo "📄 Keeping essential docs:"
ls -1 *.md 2>/dev/null
